services:
  api:
    build:
      context: .
    ports:
      - "3000:8080"
    environment:
      - ENV=DEV
      - SERVER_PORT=8080
      - API_ENDPOINT=http://localhost:3000
      - CONTROL_PLANE_DID=did:localhost:3000
      - STORAGE_ENDPOINT=storage
      - STORAGE_PORT=6380
      - DIDCOMM_AUTH_SECRET=/run/secrets/didcommauth
      - HASH_SECRET=/run/secrets/hash_secret
      - DID_DOCUMENT=/run/params/did_document.json
      - GROUP_COUNT_LIMIT=10
    secrets:
      - didcommauth
      - hash_secret
    depends_on:
      - storage
    volumes:
      - ./params:/run/params

  storage:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
      - "8001:8001" # Redis Insight UI
    volumes:
      - storage_data:/data

volumes:
  storage_data:

secrets:
  didcommauth:
    file: ./secrets/didcommauth.json
  hash_secret:
    file: ./secrets/hash_secret.json
